name: cardiowave
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  pdf: ^3.10.7
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  process_run: ^0.13.3
  flython: ^0.2.0
  opencv_4: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/loading_page.png
